title: Split Screen
description: This is a research Project on Split Screens for games and an explanation on how to implement one on c++ with xml and sdl libraries.
remote_theme: pages-themes/dinky@v0.2.0
